common: &shared
  adapter: postgresql
  encoding: unicode
  pool: 5
  username:
  password:
  min_messages: warning

development:
  database: ticket_mule_development
  <<: *shared

test:
  database: ticket_mule_test
  <<: *shared

production:
  database: ticket_mule_production
  <<: *shared
